//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioVolna.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioVolna.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Volna.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ About App.
        /// </summary>
        internal static string BtnAbout {
            get {
                return ResourceManager.GetString("BtnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add station to autostart.
        /// </summary>
        internal static string BtnAddAutoStart {
            get {
                return ResourceManager.GetString("BtnAddAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ EXIT.
        /// </summary>
        internal static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌍 Change Language.
        /// </summary>
        internal static string BtnLanguage {
            get {
                return ResourceManager.GetString("BtnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏸ PAUSE.
        /// </summary>
        internal static string BtnPause {
            get {
                return ResourceManager.GetString("BtnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ RESUME.
        /// </summary>
        internal static string BtnResume {
            get {
                return ResourceManager.GetString("BtnResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≡ STATIONS LIST.
        /// </summary>
        internal static string BtnStationList {
            get {
                return ResourceManager.GetString("BtnStationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎨 Change Theme.
        /// </summary>
        internal static string BtnTheme {
            get {
                return ResourceManager.GetString("BtnTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string DialogLangTitle {
            get {
                return ResourceManager.GetString("DialogLangTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart station:.
        /// </summary>
        internal static string LabelAutoStartStation {
            get {
                return ResourceManager.GetString("LabelAutoStartStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost. Retrying.
        /// </summary>
        internal static string LogReconnectTry {
            get {
                return ResourceManager.GetString("LogReconnectTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Volna
        ///FNKMG
        ///v{0}
        ///© 2026.
        /// </summary>
        internal static string MsgAboutBody {
            get {
                return ResourceManager.GetString("MsgAboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to autostart.
        /// </summary>
        internal static string MsgAddedToAutoStart {
            get {
                return ResourceManager.GetString("MsgAddedToAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart:.
        /// </summary>
        internal static string MsgAutoStartPrefix {
            get {
                return ResourceManager.GetString("MsgAutoStartPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No station selected.
        /// </summary>
        internal static string MsgNoStationSelected {
            get {
                return ResourceManager.GetString("MsgNoStationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select station.
        /// </summary>
        internal static string MsgSelectStation {
            get {
                return ResourceManager.GetString("MsgSelectStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load station list..
        /// </summary>
        internal static string MsgStationListError {
            get {
                return ResourceManager.GetString("MsgStationListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string NotifActionPause {
            get {
                return ResourceManager.GetString("NotifActionPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio control notification.
        /// </summary>
        internal static string NotifChannelDesc {
            get {
                return ResourceManager.GetString("NotifChannelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Volna Player.
        /// </summary>
        internal static string NotifChannelName {
            get {
                return ResourceManager.GetString("NotifChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string NotifPaused {
            get {
                return ResourceManager.GetString("NotifPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio focus busy.
        /// </summary>
        internal static string StatusAudioBusy {
            get {
                return ResourceManager.GetString("StatusAudioBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering....
        /// </summary>
        internal static string StatusBuffering {
            get {
                return ResourceManager.GetString("StatusBuffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking stream....
        /// </summary>
        internal static string StatusCheckingStream {
            get {
                return ResourceManager.GetString("StatusCheckingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No connection.
        /// </summary>
        internal static string StatusConnectionError {
            get {
                return ResourceManager.GetString("StatusConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error (Exo):.
        /// </summary>
        internal static string StatusErrorExo {
            get {
                return ResourceManager.GetString("StatusErrorExo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network / Error.
        /// </summary>
        internal static string StatusErrorNetworkGeneric {
            get {
                return ResourceManager.GetString("StatusErrorNetworkGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No network.
        /// </summary>
        internal static string StatusNoNetwork {
            get {
                return ResourceManager.GetString("StatusNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing:.
        /// </summary>
        internal static string StatusPlaying {
            get {
                return ResourceManager.GetString("StatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing (Exo):.
        /// </summary>
        internal static string StatusPlayingExo {
            get {
                return ResourceManager.GetString("StatusPlayingExo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing....
        /// </summary>
        internal static string StatusPlayingGeneric {
            get {
                return ResourceManager.GetString("StatusPlayingGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak signal... Reconnecting.
        /// </summary>
        internal static string StatusWeakSignal {
            get {
                return ResourceManager.GetString("StatusWeakSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
    }
}
